name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '17'
       cache: 'gradle'
    - run: ./gradlew build

    - name: Build and Test
      run: |
          ./gradlew --console=plain build
          ./gradlew --console=plain test
          ./gradlew --console=plain jacocoTestReport
          ./gradlew --console=plain jacocoTestCoverageVerification

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: build/reports
